// components/FullPageHeader.tsx
import Image from 'next/image';
import { SocialLinks } from './SocialLinks';

export const FullPageHeader = () => {
  return (
    <header>
      <nav className="z-10 absolute top-0 left-0 right-0 flex flex-wrap items-center content-between py-3 px-4">
        <div className="flex flex-row mx-auto order-2 lg:order-3">
          <SocialLinks className="text-white drop-shadow-lg" />
        </div>
      </nav>

      <div className="view">
        <div className="full-bg-img">
          <div className="mask mask-ink flex-center">
            <div className="container mx-auto px-4 text-white text-center animate-entrance">
              <div className="relative inline-block mb-8">
                <Image
                  id="headshot"
                  className="inline rounded-full object-cover profile-image"
                  src="/profile-cartoon-crop.jpg"
                  alt="Jacob Schulzetenberg headshot"
                  width={250}
                  height={250}
                  priority
                  placeholder="blur"
                  blurDataURL="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAABAAEDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAv/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdABmX/9k="
                  style={{
                    width: '250px',
                    height: '250px',
                    borderRadius: '125px',
                    filter: 'drop-shadow(0 6px 20px rgba(2, 6, 23, 0.35))',
                  }}
                />
              </div>

              <h1 className="pb-6">
                <div className="mb-4 text-3xl md:text-4xl font-light text-indigo-100">Hello, I&apos;m</div>
                <div className="text-5xl md:text-6xl heading-display text-white font-extrabold tracking-wide">
                  Jacob <span className="ml-3"></span> Schulzetenberg
                </div>
              </h1>

              <h2 className="text-base md:text-lg subhead-text text-indigo-50 max-w-2xl mx-auto leading-relaxed">
                <span className="inline-block rounded-lg px-4 py-2">
                  A full-stack software engineer with a passion for web development, analytics, and finance
                </span>
              </h2>
            </div>
          </div>
        </div>
      </div>
    </header>
  );
};

// OLD/src/app/full-page-header/full-page-header.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from '@angular/core';
import gsap from 'gsap';

@Component({
  selector: 'app-full-page-header',
  templateUrl: './full-page-header.component.html',
  styleUrls: ['./full-page-header.component.scss'],
})
export class FullPageHeaderComponent implements AfterViewInit {
  // eslint-disable-next-line
  constructor() {}

  @ViewChild('headshot') chidlHeadshot: ElementRef;

  @ViewChild('h1') childH1: ElementRef;

  @ViewChild('h2') childH2: ElementRef;

  ngAfterViewInit() {
    const tl = gsap.timeline({ defaults: { ease: 'power4.inOut', duration: 1, opacity: 1, y: 0 } });
    const headshot: Element = this.chidlHeadshot.nativeElement;
    const h1: Element = this.childH1.nativeElement;
    const h2: Element = this.childH2.nativeElement;

    tl.to(headshot, {});
    tl.to(h1, { 'clip-path': 'polygon(0% 100%, 100% 100%, 100% 0%, 0% 0%)', scale: 1.25 }, '-=1');
    tl.to(h2, { 'clip-path': 'polygon(0% 100%, 100% 100%, 100% 0%, 0% 0%)' }, '-=1');
  }
}

<header>
  <nav class="z-[1] relative flex flex-wrap items-center content-between py-3 px-4 text-black">
    <div class="flex flex-row mx-auto order-2 lg:order-3">
      <ul class="flex flex-wrap list-reset pl-0 mb-0 flex-row">
        <li>
          <a class="nav-link inline-block py-2 px-4 no-underline" href="https://www.linkedin.com/in/schulzetenberg" target="default">
            <i class="fa fa-2x fa-linkedin-square" aria-label="LinkedIn Icon"></i>
            <span class="sr-only">Navigate to LinkedIn profile</span>
          </a>
        </li>
        <li>
          <a class="nav-link inline-block py-2 px-4 no-underline" href="https://www.instagram.com/schulzetenberg" target="default">
            <i class="fa fa-2x fa-instagram" aria-label="Instagram Icon"></i>
            <span class="sr-only">Navigate to Instagram profile</span>
          </a>
        </li>
        <li>
          <a class="nav-link inline-block py-2 px-4 no-underline" href="https://open.spotify.com/user/waterland15" target="default">
            <i class="fa fa-2x fa-spotify" aria-label="Spotify Icon"></i>
            <span class="sr-only">Navigate to Spotify profile</span>
          </a>
        </li>
        <li>
          <a class="nav-link inline-block py-2 px-4 no-underline" href="https://github.com/schulzetenberg" target="default">
            <i class="fa fa-2x fa-github-square" aria-label="Github Icon"></i>
            <span class="sr-only">Navigate to Github profile</span>
          </a>
        </li>
      </ul>
    </div>
  </nav>

  <div class="view">
    <div class="full-bg-img">
      <div class="mask blue-light flex-center">
        <div class="container mx-auto sm:px-4 text-white text-center">
          <img id="headshot" class="inline mb-5" #headshot alt="headshot" src="assets/img/profile-cartoon-crop.jpg" aria-hidden="true" />
          <h1 #h1 class="h2 pb-2">
            <div>I am Jacob Schulzetenberg</div>
          </h1>
          <h2 #h2 class="h6">
            <div>
              A software engineer with an interest in <br />
              web development, analytics, and finance
            </div>
          </h2>
        </div>
      </div>
    </div>
  </div>
</header>
