// src/app/footer/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss'],
})
export class FooterComponent {
  copyrightYear: number;

  constructor() {
    this.copyrightYear = new Date().getFullYear();
  }
}

<footer class="page-footer elegant-color text-center pt-5">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
          <h3 class="h3-responsive color-main pb-3">Get In Touch</h3>
          <a href="mailto:Jacob.Schulzetenberg@gmail.com" class="my-5 text-white" target="default">
            <strong>Jacob.Schulzetenberg@gmail.com</strong>
          </a>
      </div>
    </div>
  </div>

  <div class="text-center py-4">
    <a
      class="btn-floating social-link waves-light mx-3"
      mdbWavesEffect
      href="http://www.linkedin.com/in/schulzetenberg"
      target="default">
        <i class="fa fa-linkedin-square"></i>
    </a>
    <a
      class="btn-floating social-link waves-light mx-3"
      mdbWavesEffect
      href="http://blog.schulzetenberg.com"
      target="default">
        <i class="fa fa-wordpress" style="font-size: 90%;"></i>
    </a>
    <a
      class="btn-floating social-link waves-light mx-3"
      mdbWavesEffect
      href="https://www.instagram.com/schulzetenberg"
      target="default">
        <i class="fa fa-instagram"></i>
    </a>
    <a
      class="btn-floating social-link waves-light mx-3"
      mdbWavesEffect
      href="https://twitter.com/schulzetenberg"
      target="default">
        <i class="fa fa-twitter-square"></i>
    </a>
    <a
      class="btn-floating social-link waves-light mx-3"
      mdbWavesEffect
      href="https://play.spotify.com/user/1210741906"
      target="default">
        <i class="fa fa-spotify"></i>
    </a>
    <a
      class="btn-floating social-link waves-light mx-3"
      mdbWavesEffect
      href="https://github.com/schulzetenberg"
      target="default">
        <i class="fa fa-github-square"></i>
    </a>
  </div>
  <div class="container-fluid text-center pb-5 grey-text">
    <small>© Copyright 2018 Jacob Schulzetenberg</small>
  </div>
</footer>

// components/Footer.tsx
'use client';

import { SocialLinks } from './SocialLinks';

export const Footer = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="page-footer elegant-color text-center pb-4 pt-32">
      <div className="container mx-auto px-4 pb-5">
        <div className="flex flex-wrap">
          <div className="w-full px-4 text-center">
            <h1 className="h1 text-4xl md:text-5xl color-main font-light mb-8" style={{ transform: 'scaleY(1.25)' }}>
              Get In Touch
            </h1>
          </div>
        </div>
      </div>

      <div className="text-center pb-24">
        <SocialLinks size="medium" className="justify-center gap-8" />
      </div>

      <div className="container mx-auto max-w-full text-center grey-text mt-5 mb-1">
        <small>© Copyright {currentYear} Jacob Schulzetenberg</small>
      </div>
    </footer>
  );
};
